<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Oism.Insights.Application/Oism.Insights.Application.csproj" />
    <ProjectReference Include="../Oism.Insights.Domain/Oism.Insights.Domain.csproj" />
    <ProjectReference Include="../../../../shared/Oism.BuildingBlocks/Oism.BuildingBlocks.csproj" />
    <ProjectReference Include="../../../../shared/Oism.Contracts/Oism.Contracts.csproj" />
  </ItemGroup>
</Project>
